### ISSUE TITLE
Is this yours now?

### ISSUE THREAD

**Issue by da-mask** [rw4lll/livewire-devtools#4]
Shouldn't this have been a pull request on the original repo, instead of forking and putting it on the Chrome web store yourself?

**Comment by rw4lll** [comment]
@da-mask it's not possible to make a PR without forking, as I'm not a maintainer of the original repo.
Yes, you're right. Normally this would definitely makes sense to do the way you wrote, but unfortunately, not this time.
 
This summer the extension was marked as a virus by chrome and disappeared from the store. The ticket with the issue was opened for several months without any updates. I've looked at the repo and found, that the last update was more than a year ago, so probably it's abandoned.

Since our team was working with livewire a lot and it was unclear, when the issue will be solved, I've decided to investigate the issue by myself and re-publish the extension ASAP to make it available for everyone again.

I thought, that probably the author will contact me to discuss about merging this updates afterwards, but on the moment it didn't happened.

Additionally I have some plans to improve this extension and currently working on it (see roadmap). On the moment the future is unclear - probably these and future updates will be merged in the main project or will become a completely separate.

**Comment by da-mask** [comment]
I understand it took a lot of work to fix, and appreciate you doing so and re-releasing this extension. Many teams have become reliant on this tool. 

I do also think you have to be careful when releasing work based on other Open source projects. I note the author of the original actually would have preferred a PR, as [mentioned here](https://github.com/beyondcode/livewire-devtools/issues/21#issuecomment-1208437668). I just hope you made enough effort to reach out to them before taking it over.

Cheers.
